// This file is generated by scripts/gct/generate-gct-specs.mjs.
// Do not edit by hand.
import type { SidebarModule } from '@/utils/constants';

export const GCT_EDHR_MENU_MODULE: SidebarModule = {
  "id": "gct-edhr",
  "label": "GCT",
  "icon": "Dashboard",
  "menus": [
    {
      "label": "操作面板",
      "icon": "Dashboard",
      "children": [
        {
          "label": "工作台",
          "path": "/gct-edhr/operation-panel/workbench/workbench-1-1"
        }
      ]
    },
    {
      "label": "基础建模",
      "icon": "AccountTree",
      "children": [
        {
          "label": "车间建模",
          "path": "/gct-edhr/basic-modeling/factory-modeling/workshop-modeling-2-1"
        },
        {
          "label": "产品家族",
          "path": "/gct-edhr/basic-modeling/product-modeling/product-family-2-2"
        },
        {
          "label": "产品列表",
          "path": "/gct-edhr/basic-modeling/product-modeling/product-list-2-3"
        },
        {
          "label": "SOP文档",
          "path": "/gct-edhr/basic-modeling/product-modeling/sop-document-2-4"
        },
        {
          "label": "单位建模",
          "path": "/gct-edhr/basic-modeling/product-modeling/unit-modeling-2-5"
        },
        {
          "label": "设备类型",
          "path": "/gct-edhr/basic-modeling/equipment-modeling/equipment-type-2-6"
        },
        {
          "label": "设备列表",
          "path": "/gct-edhr/basic-modeling/equipment-modeling/equipment-list-2-7"
        },
        {
          "label": "表单模板",
          "path": "/gct-edhr/basic-modeling/template-modeling/form-template-2-8"
        },
        {
          "label": "DHR模板",
          "path": "/gct-edhr/basic-modeling/template-modeling/dhr-template-2-9"
        },
        {
          "label": "流转单模板",
          "path": "/gct-edhr/basic-modeling/template-modeling/routing-ticket-template-2-10"
        },
        {
          "label": "编码规则",
          "path": "/gct-edhr/basic-modeling/template-modeling/coding-rule-2-11"
        },
        {
          "label": "工序建模",
          "path": "/gct-edhr/basic-modeling/process-modeling/operation-modeling-2-12"
        },
        {
          "label": "工艺路线",
          "path": "/gct-edhr/basic-modeling/process-modeling/process-route-2-13"
        },
        {
          "label": "制程配置",
          "path": "/gct-edhr/basic-modeling/process-modeling/process-configuration-2-14"
        },
        {
          "label": "不良分类",
          "path": "/gct-edhr/basic-modeling/reason-modeling/defect-category-2-15"
        },
        {
          "label": "不良原因",
          "path": "/gct-edhr/basic-modeling/reason-modeling/defect-reason-2-16"
        },
        {
          "label": "报废分类",
          "path": "/gct-edhr/basic-modeling/reason-modeling/scrap-category-2-17"
        },
        {
          "label": "报废原因",
          "path": "/gct-edhr/basic-modeling/reason-modeling/scrap-reason-2-18"
        },
        {
          "label": "审核流程",
          "path": "/gct-edhr/basic-modeling/workflow-modeling/approval-workflow-2-19"
        },
        {
          "label": "流程日志",
          "path": "/gct-edhr/basic-modeling/workflow-modeling/workflow-log-2-20"
        },
        {
          "label": "流程干预",
          "path": "/gct-edhr/basic-modeling/workflow-modeling/workflow-intervention-2-21"
        },
        {
          "label": "标签参数",
          "path": "/gct-edhr/basic-modeling/label-modeling/label-parameter-2-22"
        },
        {
          "label": "标签模板",
          "path": "/gct-edhr/basic-modeling/label-modeling/label-template-2-23"
        },
        {
          "label": "解析规则",
          "path": "/gct-edhr/basic-modeling/label-modeling/parsing-rule-2-24"
        }
      ]
    },
    {
      "label": "生产管理",
      "icon": "PrecisionManufacturing",
      "children": [
        {
          "label": "工单管理",
          "path": "/gct-edhr/production-management/production-preparation/work-order-management-3-1"
        },
        {
          "label": "批次管理",
          "path": "/gct-edhr/production-management/production-preparation/batch-management-3-2"
        },
        {
          "label": "SN管理",
          "path": "/gct-edhr/production-management/production-preparation/serial-management-3-3"
        },
        {
          "label": "生产执行",
          "path": "/gct-edhr/production-management/batch-production/production-execution-3-4"
        },
        {
          "label": "返工执行",
          "path": "/gct-edhr/production-management/batch-production/rework-execution-3-5"
        },
        {
          "label": "批次事务",
          "path": "/gct-edhr/production-management/batch-production/batch-transaction-3-6"
        },
        {
          "label": "返工列表",
          "path": "/gct-edhr/production-management/batch-production/rework-list-3-7"
        },
        {
          "label": "生产执行",
          "path": "/gct-edhr/production-management/serial-production/production-execution-3-8"
        },
        {
          "label": "返工执行",
          "path": "/gct-edhr/production-management/serial-production/rework-execution-3-9"
        },
        {
          "label": "SN事务",
          "path": "/gct-edhr/production-management/serial-production/serial-transaction-3-10"
        },
        {
          "label": "返工列表",
          "path": "/gct-edhr/production-management/serial-production/rework-list-3-11"
        },
        {
          "label": "事务列表",
          "path": "/gct-edhr/production-management/production-configuration/transaction-list-3-12"
        },
        {
          "label": "事务配置",
          "path": "/gct-edhr/production-management/production-configuration/transaction-configuration-3-13"
        }
      ]
    },
    {
      "label": "检验管理",
      "icon": "Storage",
      "children": [
        {
          "label": "检验执行",
          "path": "/gct-edhr/inspection-management/inspection-operations/inspection-execution-4-1"
        },
        {
          "label": "检验列表",
          "path": "/gct-edhr/inspection-management/inspection-operations/inspection-list-4-2"
        },
        {
          "label": "检验事务",
          "path": "/gct-edhr/inspection-management/inspection-operations/inspection-transaction-4-3"
        },
        {
          "label": "检验方法",
          "path": "/gct-edhr/inspection-management/inspection-modeling/inspection-method-4-4"
        },
        {
          "label": "检验项目",
          "path": "/gct-edhr/inspection-management/inspection-modeling/inspection-item-4-5"
        },
        {
          "label": "检验分类",
          "path": "/gct-edhr/inspection-management/inspection-modeling/inspection-category-4-6"
        },
        {
          "label": "检验方案",
          "path": "/gct-edhr/inspection-management/inspection-modeling/inspection-plan-4-7"
        },
        {
          "label": "检验规程",
          "path": "/gct-edhr/inspection-management/inspection-configuration/inspection-procedure-4-8"
        },
        {
          "label": "事务配置",
          "path": "/gct-edhr/inspection-management/inspection-configuration/transaction-configuration-4-9"
        },
        {
          "label": "事务列表",
          "path": "/gct-edhr/inspection-management/inspection-configuration/transaction-list-4-10"
        }
      ]
    },
    {
      "label": "放行管理",
      "icon": "Storage",
      "children": [
        {
          "label": "放行列表",
          "path": "/gct-edhr/release-management/release-operations/release-list-5-1"
        },
        {
          "label": "放行规程",
          "path": "/gct-edhr/release-management/release-configuration/release-procedure-5-2"
        },
        {
          "label": "事务配置",
          "path": "/gct-edhr/release-management/release-configuration/transaction-configuration-5-3"
        },
        {
          "label": "事务列表",
          "path": "/gct-edhr/release-management/release-configuration/transaction-list-5-4"
        }
      ]
    },
    {
      "label": "记录管理",
      "icon": "Storage",
      "children": [
        {
          "label": "表单填报",
          "path": "/gct-edhr/record-management/form-management/form-filling-6-1"
        },
        {
          "label": "表单审核",
          "path": "/gct-edhr/record-management/form-management/form-approval-6-2"
        },
        {
          "label": "表单列表",
          "path": "/gct-edhr/record-management/form-management/form-list-6-3"
        },
        {
          "label": "DHR填报",
          "path": "/gct-edhr/record-management/dhr-management/dhr-filling-6-4"
        },
        {
          "label": "DHR汇总",
          "path": "/gct-edhr/record-management/dhr-management/dhr-summary-6-5"
        },
        {
          "label": "DHR审核",
          "path": "/gct-edhr/record-management/dhr-management/dhr-approval-6-6"
        },
        {
          "label": "DHR列表",
          "path": "/gct-edhr/record-management/dhr-management/dhr-list-6-7"
        },
        {
          "label": "我的记录本",
          "path": "/gct-edhr/record-management/record-book/my-record-book-6-8"
        },
        {
          "label": "记录本填报",
          "path": "/gct-edhr/record-management/record-book/record-book-filling-6-9"
        },
        {
          "label": "记录本列表",
          "path": "/gct-edhr/record-management/record-book/record-book-list-6-10"
        },
        {
          "label": "记录本标签",
          "path": "/gct-edhr/record-management/record-book/record-book-label-6-11"
        },
        {
          "label": "表单变更",
          "path": "/gct-edhr/record-management/change-management/form-change-6-12"
        },
        {
          "label": "DHR变更",
          "path": "/gct-edhr/record-management/change-management/dhr-change-6-13"
        },
        {
          "label": "记录本变更",
          "path": "/gct-edhr/record-management/change-management/record-book-change-6-14"
        },
        {
          "label": "变更审核",
          "path": "/gct-edhr/record-management/change-management/change-approval-6-15"
        },
        {
          "label": "我的打印",
          "path": "/gct-edhr/record-management/record-printing/my-printing-6-16"
        },
        {
          "label": "打印列表",
          "path": "/gct-edhr/record-management/record-printing/print-list-6-17"
        }
      ]
    },
    {
      "label": "统计报表",
      "icon": "Dashboard",
      "children": [
        {
          "label": "生产追溯",
          "path": "/gct-edhr/statistics-reports/reports/production-traceability-7-1"
        },
        {
          "label": "检验追溯",
          "path": "/gct-edhr/statistics-reports/reports/inspection-traceability-7-2"
        },
        {
          "label": "放行追溯",
          "path": "/gct-edhr/statistics-reports/reports/release-traceability-7-3"
        },
        {
          "label": "表单追溯",
          "path": "/gct-edhr/statistics-reports/reports/form-traceability-7-4"
        },
        {
          "label": "DHR追溯",
          "path": "/gct-edhr/statistics-reports/reports/dhr-traceability-7-5"
        },
        {
          "label": "记录本追溯",
          "path": "/gct-edhr/statistics-reports/reports/record-book-traceability-7-6"
        },
        {
          "label": "报工记录",
          "path": "/gct-edhr/statistics-reports/reports/work-report-record-7-7"
        },
        {
          "label": "报废记录",
          "path": "/gct-edhr/statistics-reports/reports/scrap-record-7-8"
        },
        {
          "label": "消耗记录",
          "path": "/gct-edhr/statistics-reports/reports/consumption-record-7-9"
        },
        {
          "label": "消息记录",
          "path": "/gct-edhr/statistics-reports/reports/message-record-7-10"
        },
        {
          "label": "标签记录",
          "path": "/gct-edhr/statistics-reports/reports/label-record-7-11"
        },
        {
          "label": "运营座舱",
          "path": "/gct-edhr/statistics-reports/dashboards/operations-cockpit-7-12"
        },
        {
          "label": "生产监控",
          "path": "/gct-edhr/statistics-reports/dashboards/production-monitoring-7-13"
        },
        {
          "label": "品质监控",
          "path": "/gct-edhr/statistics-reports/dashboards/quality-monitoring-7-14"
        },
        {
          "label": "数据集",
          "path": "/gct-edhr/statistics-reports/custom-reporting/dataset-7-15"
        },
        {
          "label": "报表查看",
          "path": "/gct-edhr/statistics-reports/custom-reporting/report-view-7-16"
        },
        {
          "label": "报表设计",
          "path": "/gct-edhr/statistics-reports/custom-reporting/report-design-7-17"
        }
      ]
    },
    {
      "label": "系统管理",
      "icon": "Settings",
      "children": [
        {
          "label": "用户管理",
          "path": "/gct-edhr/system-management/organization-permissions/user-management-8-1"
        },
        {
          "label": "组织成员",
          "path": "/gct-edhr/system-management/organization-permissions/organization-member-8-2"
        },
        {
          "label": "角色管理",
          "path": "/gct-edhr/system-management/organization-permissions/role-management-8-3"
        },
        {
          "label": "权限管理",
          "path": "/gct-edhr/system-management/organization-permissions/permission-management-8-4"
        },
        {
          "label": "用户席位",
          "path": "/gct-edhr/system-management/organization-permissions/user-seat-8-5"
        },
        {
          "label": "连接流",
          "path": "/gct-edhr/system-management/integration-center/connection-flow-8-6"
        },
        {
          "label": "连接器",
          "path": "/gct-edhr/system-management/integration-center/connector-8-7"
        },
        {
          "label": "数据源",
          "path": "/gct-edhr/system-management/integration-center/data-source-8-8"
        },
        {
          "label": "设备互联",
          "path": "/gct-edhr/system-management/integration-center/equipment-connectivity-8-9"
        },
        {
          "label": "数据追溯",
          "path": "/gct-edhr/system-management/audit-tracking/data-traceability-8-10"
        },
        {
          "label": "登录日志",
          "path": "/gct-edhr/system-management/audit-tracking/login-log-8-11"
        },
        {
          "label": "系统设置",
          "path": "/gct-edhr/system-management/system-configuration/system-settings-8-12"
        },
        {
          "label": "模型设置",
          "path": "/gct-edhr/system-management/system-configuration/model-settings-8-13"
        }
      ]
    }
  ]
}
