import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Add, Cancel, Edit, Search } from '@mui/icons-material';
import { Alert, Box, Button, CircularProgress, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Pagination, Select, Snackbar, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material';
import AppDialog from '@/components/AppDialog';
import ConfirmDialog from '@/components/ConfirmDialog';
import { getProductModelingProducts, getProductModelWorkspace, type ProductModelSource, type ProductProcessVersion } from '@/api/product-modeling';
import { cancelWorkOrder, createWorkOrder, listWorkOrders, updateWorkOrder, type WorkOrder } from '@/api/work-orders';
import type { PageResult } from '@/types/common';

const PAGE_SIZE = 20;
const statusLabels: Record<string, string> = { CREATED: '已创建', IN_PROCESS: '生产中', COMPLETED: '已完成', CLOSED: '已关闭', CANCELLED: '已取消' };
const formLabels: Record<string, string> = { SN: 'SN', 批次: '批次', '批次转SN': '批次转SN' };
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }).replace(/\//g, '-') : '-';

export default function WorkOrderPage() {
  const client = useQueryClient();
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [submittedKeyword, setSubmittedKeyword] = useState('');
  const [status, setStatus] = useState(''); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<WorkOrder | null>(null);
  const [cancelTarget, setCancelTarget] = useState<WorkOrder | null>(null);
  const [form, setForm] = useState({ productId: '', processVersionId: '', plannedQuantity: '', remark: '' });
  const [message, setMessage] = useState<{ text: string; error?: boolean } | null>(null);
  const orders = useQuery({ queryKey: ['work-orders', page, submittedKeyword, status], queryFn: async () => (await listWorkOrders({ page, size: PAGE_SIZE, keyword: submittedKeyword, status })).data.data as PageResult<WorkOrder> });
  const products = useQuery({ queryKey: ['work-order-products'], queryFn: async () => (await getProductModelingProducts({ page: 1, size: 500, status: 'ACTIVE' })).data.data as PageResult<ProductModelSource> });
  const process = useQuery({ queryKey: ['work-order-process', form.productId], enabled: Boolean(form.productId), queryFn: async () => (await getProductModelWorkspace(form.productId)).data.data });
  const save = useMutation({ mutationFn: () => { const body = { productId: form.productId, processVersionId: form.processVersionId, plannedQuantity: Number(form.plannedQuantity), remark: form.remark }; return editing ? updateWorkOrder(editing.id, body) : createWorkOrder(body); }, onSuccess: () => { client.invalidateQueries({ queryKey: ['work-orders'] }); setDialogOpen(false); setMessage({ text: editing ? '更新成功' : '创建成功' }); }, onError: (error: any) => setMessage({ text: error?.response?.data?.message || '操作失败', error: true }) });
  const cancel = useMutation({ mutationFn: cancelWorkOrder, onSuccess: () => { client.invalidateQueries({ queryKey: ['work-orders'] }); setCancelTarget(null); setMessage({ text: '工单已取消' }); }, onError: () => setMessage({ text: '取消失败', error: true }) });
  const versions: ProductProcessVersion[] = process.data?.model?.versions ?? [];
  const openCreate = () => { setEditing(null); setForm({ productId: '', processVersionId: '', plannedQuantity: '', remark: '' }); setDialogOpen(true); };
  const openEdit = (item: WorkOrder) => { setEditing(item); setForm({ productId: item.productId, processVersionId: item.processVersionId, plannedQuantity: String(item.plannedQuantity), remark: item.remark || '' }); setDialogOpen(true); };
  const selectProduct = (productId: string) => setForm((current) => ({ ...current, productId, processVersionId: '' }));
  return <Box>
    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}><Typography variant="h5">工单管理</Typography><Button variant="contained" startIcon={<Add />} onClick={openCreate}>新建工单</Button></Box>
    <Box sx={{ display: 'flex', gap: 1, mb: 2, alignItems: 'center' }}><TextField size="small" placeholder="工单号、产品名称或编码" value={keyword} onChange={(e) => setKeyword(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { setPage(1); setSubmittedKeyword(keyword); } }} /><Button variant="outlined" startIcon={<Search />} onClick={() => { setPage(1); setSubmittedKeyword(keyword); }}>查询</Button><FormControl size="small" sx={{ minWidth: 140 }}><InputLabel>状态</InputLabel><Select value={status} label="状态" onChange={(e) => { setPage(1); setStatus(e.target.value); }}><MenuItem value="">全部</MenuItem>{Object.entries(statusLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl></Box>
    <TableContainer><Table><TableHead><TableRow>{['工单号', '产品', '制程版本', '生产模式', '生产形态', '计划数量', '状态', '创建时间', '操作'].map((label) => <TableCell key={label} sx={{ bgcolor: '#f5f7fa', fontWeight: 600, whiteSpace: 'nowrap' }}>{label}</TableCell>)}</TableRow></TableHead><TableBody>
      {orders.isLoading ? <TableRow><TableCell colSpan={9} align="center"><CircularProgress size={24} /></TableCell></TableRow> : orders.isError ? <TableRow><TableCell colSpan={9} align="center">加载失败</TableCell></TableRow> : (orders.data?.content ?? []).length === 0 ? <TableRow><TableCell colSpan={9} align="center" sx={{ py: 8, color: '#909399' }}>暂无数据</TableCell></TableRow> : orders.data!.content.map((item) => <TableRow key={item.id}><TableCell>{item.orderNo}</TableCell><TableCell>{item.productName}<Typography variant="caption" display="block" color="text.secondary">{item.productCode}</Typography></TableCell><TableCell>{item.processVersion}</TableCell><TableCell>{item.productionMode}</TableCell><TableCell>{formLabels[item.productionForm] || item.productionForm}</TableCell><TableCell>{item.plannedQuantity}</TableCell><TableCell>{statusLabels[item.status] || item.status}</TableCell><TableCell>{formatDate(item.createdAt)}</TableCell><TableCell sx={{ whiteSpace: 'nowrap' }}>{item.status === 'CREATED' && <><Tooltip title="编辑"><IconButton size="small" onClick={() => openEdit(item)}><Edit fontSize="small" /></IconButton></Tooltip><Tooltip title="取消"><IconButton size="small" color="error" onClick={() => setCancelTarget(item)}><Cancel fontSize="small" /></IconButton></Tooltip></>}</TableCell></TableRow>)}
    </TableBody></Table></TableContainer>
    {orders.data && orders.data.totalPages > 1 && <Box sx={{ mt: 2, display: 'flex', justifyContent: 'center' }}><Pagination count={orders.data.totalPages} page={page} onChange={(_, value) => setPage(value)} /></Box>}
    <AppDialog open={dialogOpen} onClose={() => setDialogOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing ? '编辑工单' : '新建工单'}</DialogTitle><DialogContent><FormControl fullWidth margin="normal"><InputLabel>产品</InputLabel><Select value={form.productId} label="产品" onChange={(e) => selectProduct(e.target.value)}>{(products.data?.content ?? []).map((product) => <MenuItem key={product.id} value={String(product.id)}>{product.name}（{product.code}）</MenuItem>)}</Select></FormControl><FormControl fullWidth margin="normal" disabled={!form.productId || process.isLoading}><InputLabel>制程版本</InputLabel><Select value={form.processVersionId} label="制程版本" onChange={(e) => setForm({ ...form, processVersionId: e.target.value })}>{versions.filter((version) => version.status === 'ACTIVE').map((version) => <MenuItem key={version.id} value={version.id}>{version.version} / {version.productionMode} / {formLabels[version.productionForm] || version.productionForm}</MenuItem>)}</Select></FormControl>{form.processVersionId && <Alert severity="info" sx={{ mt: 1 }}>生产模式：{versions.find((version) => version.id === form.processVersionId)?.productionMode}；生产形态：{formLabels[versions.find((version) => version.id === form.processVersionId)?.productionForm || ''] || versions.find((version) => version.id === form.processVersionId)?.productionForm}</Alert>}<TextField fullWidth margin="normal" label="计划数量" type="number" inputProps={{ min: 0, step: 'any' }} value={form.plannedQuantity} onChange={(e) => setForm({ ...form, plannedQuantity: e.target.value })} /><TextField fullWidth margin="normal" label="备注" multiline minRows={3} value={form.remark} onChange={(e) => setForm({ ...form, remark: e.target.value })} /></DialogContent><DialogActions><Button onClick={() => setDialogOpen(false)}>取消</Button><Button variant="contained" onClick={() => save.mutate()} disabled={!form.productId || !form.processVersionId || Number(form.plannedQuantity) <= 0 || save.isPending}>保存</Button></DialogActions></AppDialog>
    <ConfirmDialog open={cancelTarget !== null} title="取消工单" message={cancelTarget ? `确定取消工单「${cancelTarget.orderNo}」吗？` : ''} confirmText="取消工单" destructive loading={cancel.isPending} onCancel={() => setCancelTarget(null)} onConfirm={() => cancelTarget && cancel.mutate(cancelTarget.id)} />
    <Snackbar open={Boolean(message)} autoHideDuration={3000} onClose={() => setMessage(null)}><Alert severity={message?.error ? 'error' : 'success'} onClose={() => setMessage(null)}>{message?.text}</Alert></Snackbar>
  </Box>;
}
