ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS operator_account VARCHAR(128);
ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS module_name VARCHAR(128);
ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS menu_name VARCHAR(128);
ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS function_name VARCHAR(128);
ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS data_summary VARCHAR(512);
